version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/server/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/client/"
    schedule:
      interval: "monthly"
