name: ci

on:
  schedule:
    # build every first of the month
    - cron: '0 0 1 * *'
  push:
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: [ 'client', 'server' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.php }}
        id: docker_build_latest
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.directory }}"
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/andersundsehr/vm-proxy-${{ matrix.directory }},ghcr.io/andersundsehr/vm-proxy-${{ matrix.directory }}:${{ steps.date.outputs.date }},andersundsehr/vm-proxy-${{ matrix.directory }},andersundsehr/vm-proxy-${{ matrix.directory }}:${{ steps.date.outputs.date }}
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_dev.outputs.digest }}
